version: 2.1
orbs:
  architect: giantswarm/architect@4.8.1

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/docker-helm"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            tags:
              only: /^v.*/
